"""sync all models with database

Revision ID: 9cd74786500a
Revises: 7aaf2d6aa143
Create Date: 2026-02-07 06:41:30.467107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd74786500a'
down_revision: Union[str, Sequence[str], None] = '7aaf2d6aa143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=True),
    sa.Column('location_address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_code')
    )
    op.create_table('boxes',
    sa.Column('box_id', sa.BigInteger(), nullable=False),
    sa.Column('box_name', sa.String(length=100), nullable=False),
    sa.Column('box_code', sa.String(length=45), nullable=True),
    sa.Column('box_ip', sa.String(length=45), nullable=True),
    sa.Column('box_netmask', sa.String(length=45), nullable=True),
    sa.Column('box_gateway', sa.String(length=45), nullable=True),
    sa.Column('box_dns', sa.String(length=45), nullable=True),
    sa.Column('box_ntp', sa.String(length=45), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('box_status', sa.String(length=20), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('box_id')
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_jti', sa.String(length=36), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('token_jti')
    )
    op.create_table('cameras',
    sa.Column('camera_id', sa.BigInteger(), nullable=False),
    sa.Column('camera_serial', sa.String(length=100), nullable=False),
    sa.Column('camera_name', sa.String(length=100), nullable=False),
    sa.Column('camera_model', sa.String(length=100), nullable=True),
    sa.Column('camera_type', sa.String(length=10), nullable=True),
    sa.Column('camera_code', sa.String(length=45), nullable=True),
    sa.Column('camera_ip', sa.String(length=45), nullable=True),
    sa.Column('camera_netmask', sa.String(length=45), nullable=True),
    sa.Column('camera_gateway', sa.String(length=45), nullable=True),
    sa.Column('camera_dns', sa.String(length=45), nullable=True),
    sa.Column('camera_ntp', sa.String(length=45), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('box_id', sa.BigInteger(), nullable=True),
    sa.Column('stream_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.box_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('camera_id'),
    sa.UniqueConstraint('camera_serial')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cameras')
    op.drop_table('user_sessions')
    op.drop_table('boxes')
    op.drop_table('locations')
    # ### end Alembic commands ###
